name: ai_tools_fine_tuning
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - accelerate=1.12.0=pyhcf101f3_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=py313hd6074c6_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alsa-lib=1.2.15.3=hb03c661_0
  - anyio=4.12.1=pyhcf101f3_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py313h07c4f96_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.1.0=pyhcf101f3_0
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.3=hef928c7_0
  - aws-c-cal=0.9.13=h2c9d079_1
  - aws-c-common=0.12.6=hb03c661_0
  - aws-c-compression=0.3.1=h8b1a151_9
  - aws-c-event-stream=0.5.7=h28f887f_1
  - aws-c-http=0.10.7=ha8fc4e3_5
  - aws-c-io=0.23.3=hdaf4b65_5
  - aws-c-mqtt=0.13.3=hc63082f_11
  - aws-c-s3=0.11.3=h06ab39a_1
  - aws-c-sdkutils=0.2.4=h8b1a151_4
  - aws-checksums=0.2.7=h8b1a151_5
  - aws-crt-cpp=0.35.4=h8824e59_0
  - aws-sdk-cpp=1.11.606=h20b40b1_10
  - azure-core-cpp=1.16.1=h3a458e0_0
  - azure-identity-cpp=1.13.2=h3a5f585_1
  - azure-storage-blobs-cpp=12.15.0=h2a74896_1
  - azure-storage-common-cpp=12.11.0=h3d7a050_1
  - azure-storage-files-datalake-cpp=12.13.0=hf38f1be_1
  - babel=2.17.0=pyhd8ed1ab_0
  - backports.zstd=1.3.0=py313h18e8e13_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - bitsandbytes=0.49.1=cuda129_py313hb03d067_200
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - brotli-python=1.2.0=py313hf159716_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=he90730b_1
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py313hf46b229_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py313h7037e92_3
  - cpython=3.13.11=py313hd8ed1ab_100
  - cuda-crt-tools=12.9.86=ha770c72_2
  - cuda-cudart=12.9.79=h5888daf_0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-cuobjdump=12.9.82=hffce074_1
  - cuda-cupti=12.9.79=h676940d_1
  - cuda-nvcc-tools=12.9.86=he02047a_2
  - cuda-nvdisasm=12.9.88=hffce074_1
  - cuda-nvrtc=12.9.86=hecca717_1
  - cuda-nvtx=12.9.79=hecca717_1
  - cuda-nvvm-tools=12.9.86=h4bc722e_2
  - cuda-version=12.9=h4f385c5_3
  - cudnn=9.10.2.21=hbcb9cd8_0
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=hd9c7081_0
  - datasets=4.4.2=pyhcf101f3_0
  - dbus=1.16.2=h24cb091_1
  - debugpy=1.8.19=py313hb7f33ac_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.4.0=pyhcf101f3_1
  - double-conversion=3.4.0=hecca717_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - filelock=3.20.3=pyhd8ed1ab_0
  - fmt=12.1.0=hff5e90c_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py313h3dea7bd_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=ha770c72_0
  - frozenlist=1.7.0=py313h6b9daa2_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - gflags=2.2.2=h5888daf_1005
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py313h86d8783_2
  - graphite2=1.3.14=hecca717_2
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.3.0=h6083320_0
  - hf-xet=1.2.1=py310hb823017_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_hub=0.36.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h33c6efd_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.9.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - json5=0.13.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.26.0=pyhcf101f3_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.26.0=hcf101f3_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.4=pyhcf101f3_0
  - jupyterlab=4.5.2=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py313hc8edb43_2
  - krb5=1.21.3=h659f571_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.18=h0c24ade_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libarrow=22.0.0=hb6ed5f4_6_cpu
  - libarrow-acero=22.0.0=h635bf11_6_cpu
  - libarrow-compute=22.0.0=h8c2c5c3_6_cpu
  - libarrow-dataset=22.0.0=h635bf11_6_cpu
  - libarrow-substrait=22.0.0=h3f74fd7_6_cpu
  - libblas=3.11.0=5_h5875eb1_mkl
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcap=2.77=h3ff7636_0
  - libcblas=3.11.0=5_hfef963f_mkl
  - libclang-cpp21.1=21.1.8=default_h99862b1_1
  - libclang13=21.1.8=default_h746c552_1
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.9.1.4=h676940d_1
  - libcudnn=9.10.2.21=hf7e9902_0
  - libcudnn-dev=9.10.2.21=h58dd1b1_0
  - libcudss=0.7.1.4=h58dd1b1_0
  - libcufft=11.4.1.4=hecca717_1
  - libcufile=1.14.1.1=hbc026e6_1
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.3.10.19=h676940d_1
  - libcurl=8.18.0=h4e3cde8_0
  - libcusolver=11.7.5.82=h676940d_2
  - libcusparse=12.5.10.65=hecca717_2
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.3=h6548e54_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgrpc=1.73.1=h3288cfb_1
  - libhwloc=2.12.2=default_hafda6a7_1000
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=5_h5e43f62_mkl
  - libllvm21=21.1.8=hf7376ad_0
  - liblzma=5.8.2=hb03c661_0
  - libmagma=2.9.0=ha7672b3_6
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnghttp2=1.67.0=had1ee68_0
  - libnl=3.11.0=hb9d3cd8_0
  - libntlm=1.8=hb9d3cd8_0
  - libnvjitlink=12.9.86=hecca717_2
  - libopengl=1.7.0=ha4b6fd6_2
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libparquet=22.0.0=h7376487_6_cpu
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.54=h421ea60_0
  - libpq=18.1=hb80d175_3
  - libprotobuf=6.31.1=h49aed37_4
  - libre2-11=2025.11.05=h7b12aa8_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.2=hf4e2dac_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libsystemd0=258.3=h6569c3e_0
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.1=h9d88235_1
  - libtorch=2.9.1=cuda129_mkl_hf5f578d_303
  - libudev1=258.3=h6569c3e_0
  - libutf8proc=2.11.3=hfe17d71_0
  - libuuid=2.41.3=h5347b49_0
  - libuv=1.51.0=hb03c661_1
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.1=hca5e8e5_0
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libxslt=1.1.43=h711ed8c_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=21.1.8=h4922eb0_0
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.3=py313h3dea7bd_0
  - matplotlib=3.10.8=py313h78bf25f_0
  - matplotlib-base=3.10.8=py313h683a580_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mistune=3.2.0=pyhcf101f3_0
  - mkl=2025.3.0=h0e700b2_463
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.7.0=py313h3dea7bd_0
  - multiprocess=0.70.18=py313h54dd161_2
  - munkres=1.1.4=pyhd8ed1ab_1
  - nbclient=0.10.4=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nccl=2.29.2.1=h4d09622_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.6.1=pyhcf101f3_0
  - nlohmann_json=3.12.0=h54a6638_1
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=2.4.1=py313hf6604e3_0
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.0=h26f9b46_0
  - optree=0.18.0=py313h7037e92_0
  - orc=2.2.1=hd747db4_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=3.0.0=py313hbfd7664_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.47=haa7fec5_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=12.1.0=py313h80991f8_0
  - pip=25.3=pyh145f28c_0
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - prometheus_client=0.24.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py313h8060acc_0
  - psutil=7.2.1=py313h54dd161_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=22.0.0=py313h78bf25f_1
  - pyarrow-core=22.0.0=py313he109ebe_1_cpu
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-abi=11=hc364b38_1
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyside6=6.10.1=py313h85046ba_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.13.11=hc97d973_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.13.11=h4df99d1_100
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py313heab5758_1
  - python_abi=3.13=8_cp313
  - pytorch=2.9.1=cuda129_mkl_py313_h9830416_303
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py313h3dea7bd_0
  - pyzmq=27.1.0=py312hfb55c3c_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.10.1=hb82b983_4
  - rdma-core=60.0=hecca717_0
  - re2=2025.11.05=h5301d42_0
  - readline=8.3=h853b02a_0
  - referencing=0.37.0=pyhcf101f3_0
  - regex=2026.1.15=py313h07c4f96_0
  - requests=2.32.5=pyhcf101f3_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.30.0=py313h843e2db_0
  - s2n=1.6.2=he8a4886_1
  - safetensors=0.7.0=py313h5c7d99a_0
  - scipy=1.17.0=py313h4b8bb8b_1
  - send2trash=2.1.0=pyha191276_0
  - setuptools=80.10.1=pyh332efcf_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=ha0421bc_0
  - snappy=1.2.2=h03e3b7b_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8.3=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2022.3.0=hb700be7_2
  - terminado=0.18.1=pyhc90fa1f_1
  - tinycss2=1.5.1=pyhcf101f3_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tokenizers=0.22.2=py313h4d6fefd_0
  - tomli=2.4.0=pyhcf101f3_0
  - tornado=6.5.4=py313hd02dea0_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - transformers=4.57.6=pyhd8ed1ab_0
  - triton=3.5.1=cuda129py313h246eb7c_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025c=hc9c84f9_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - wayland=1.24.0=hd6090a7_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.6=hb03c661_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xxhash=0.8.3=hb47aa4a_0
  - yaml=0.2.5=h280c20c_3
  - yarl=1.22.0=py313h3dea7bd_0
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.3.2=hceb46e0_1
  - zstd=1.5.7=hb78ec9c_6

prefix: "/home/gjb/mambaforge/envs/ai_tools_fine_tuning"
